name = "petri_net"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PetriNet"]

[[require]]
name = "LeanArchitect"
git = "https://github.com/hanwenzhu/LeanArchitect.git"
rev = "v4.29.1"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.1"

[[lean_lib]]
name = "PetriNet"

